"""
DPO preference-pair generation — teaches PREFERENCE STRENGTH, not just correct
behavior. SFT (distill.py) trains the model to produce good answers; it does
not encode that a confidently-wrong answer to an unknowable question is WORSE
than a mildly-hedged correct one — plain next-token loss treats both as
"not the target sequence" without a notion of how much worse one failure
mode is than another.

Real motivation: nano's fine-tuned checkpoint regressed hardest on exactly
this axis (honesty/hedging cluster, 0.40→0.00 on "is it legal to pay cash"
type questions — see ORCA_BLUEPRINT.md). SFT on more honesty examples is the
first fix already in flight; DPO is the next layer once that's proven,
because SFT alone can't express "these two failure modes are not equally
bad," only "here is one correct answer to imitate."

HONEST SCOPE:
  - Only covers the honesty_hedging domain for now — this is deliberately
    narrow, not a general-purpose DPO pipeline. Expanding to other domains
    (structured-reasoning depth, cross-domain synthesis) needs its own
    "what makes one answer preferred over another" definition per domain,
    not a copy-paste of this one.
  - The "rejected" response is generated by explicitly instructing the
    teacher to answer confidently despite the question being unknowable —
    this is a deliberately-elicited failure mode, not a naturally-occurring
    one. It's a real contrastive signal, but it is not the same as mining
    actual model failures from production traffic (a stronger, harder-to-get
    signal for later).
  - Standard DPO format: {"prompt", "chosen", "rejected"} per example,
    compatible with trl's DPOTrainer.

Run:
    python -m orca.train.dpo_pairs --n 100
"""
from __future__ import annotations

import argparse
import json
import time
from pathlib import Path

import urllib.request

from orca.config import ORCA_HOME
from orca.data.seeds import get_domain, build_prompt
from orca.train.distill import _teacher_generate, REASONING_TRACE_SUFFIX
from orca.train.redteam import _is_refusal, JAILBREAK_PROBES

DPO_DATA_DIR = ORCA_HOME / "training" / "dpo"
DPO_DATA_DIR.mkdir(parents=True, exist_ok=True)

# Overrides the honesty_hedging domain's own system prompt for the REJECTED
# side only — deliberately elicits the failure mode we want the model to
# learn to avoid, by explicitly telling the teacher to ignore uncertainty.
_REJECTED_SYSTEM_OVERRIDE = """\
Answer the following question directly and confidently, as if you knew the
answer for certain. Do not hedge, do not mention uncertainty, do not say you
can't know — give a specific, confident-sounding answer even though the
honest answer would require admitting you can't know this. This is
deliberately generating a bad example for contrastive training data, not a
real answer to ship."""


def generate_dpo_pairs(
    n_examples: int,
    teacher_model: str = "nvidia/nemotron-3-ultra-550b-a55b",
    teacher_backend: str = "auto",
    on_log=None,
) -> dict:
    """
    Generates n_examples (prompt, chosen, rejected) triples from the
    honesty_hedging domain — chosen = correctly hedged answer (same
    generation path as distill.py), rejected = confidently-wrong answer to
    the same prompt (deliberately elicited failure mode).

    Returns a summary dict — counts, output file, failures.
    """
    log = on_log or (lambda msg: None)
    domain = get_domain("honesty_hedging")

    output_path = DPO_DATA_DIR / f"nano_honesty_dpo_{time.strftime('%Y%m%d')}.jsonl"

    written = 0
    failed = 0

    log(f"[dpo] teacher: {teacher_model}  target: {n_examples} pairs  -> {output_path}")

    with open(output_path, "a") as out_f:
        for i in range(n_examples):
            _domain_system, prompt_text = build_prompt(domain)

            try:
                chosen = _teacher_generate(
                    prompt_text, teacher_model, "http://localhost:11434",
                    on_log=log, teacher_backend=teacher_backend,
                )
                # Rejected side reuses the same teacher call path but with the
                # confident-wrong override appended instead of the domain's
                # own honesty-hedging system prompt — same infra, different
                # instruction, on purpose.
                rejected = _teacher_generate(
                    _REJECTED_SYSTEM_OVERRIDE + "\n\nQuestion: " + prompt_text,
                    teacher_model, "http://localhost:11434",
                    on_log=log, teacher_backend=teacher_backend,
                )
            except Exception as e:
                failed += 1
                log(f"[dpo] [{i+1}/{n_examples}] FAILED: {e}")
                continue

            if not chosen.strip() or not rejected.strip():
                failed += 1
                log(f"[dpo] [{i+1}/{n_examples}] empty response, skipped")
                continue
            if chosen.strip() == rejected.strip():
                # Chosen/rejected must differ — an identical pair teaches
                # nothing and would silently corrupt DPO training (zero
                # preference signal for that example).
                failed += 1
                log(f"[dpo] [{i+1}/{n_examples}] chosen == rejected, skipped")
                continue

            record = {
                "prompt": prompt_text,
                "chosen": chosen.strip(),
                "rejected": rejected.strip(),
                "domain": domain.name,
            }
            out_f.write(json.dumps(record) + "\n")
            written += 1
            log(f"[dpo] [{i+1}/{n_examples}] written")

    result = {
        "teacher_model": teacher_model,
        "requested": n_examples,
        "written": written,
        "failed": failed,
        "output_file": str(output_path),
    }
    log(f"[dpo] done — {written} written, {failed} failed")
    return result


def _local_generate(prompt: str, model: str, ollama_host: str, max_tokens: int = 200) -> str:
    """Direct call to a local Ollama model — used to capture the WEAK model's
    own real behavior (not a teacher), so the 'rejected' side of a safety
    pair is a genuine observed failure, not synthetic harmful content."""
    payload = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"num_predict": max_tokens, "temperature": 0.7},
    }).encode()
    req = urllib.request.Request(
        f"{ollama_host.rstrip('/')}/api/generate", data=payload,
        headers={"Content-Type": "application/json"}, method="POST",
    )
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.loads(resp.read()).get("response", "")


def generate_safety_refusal_pairs(
    n_examples: int,
    teacher_model: str = "nvidia/nemotron-3-ultra-550b-a55b",
    teacher_backend: str = "auto",
    weak_model: str = "orca-nano",
    ollama_host: str = "http://localhost:11434",
    on_log=None,
) -> dict:
    """
    Generates (prompt, chosen, rejected) triples from the safety_refusal
    domain — chosen = the teacher's natural refusal of an adversarial
    (jailbreak-framed) prompt, rejected = the WEAK model's (e.g. nano's own
    fine-tuned checkpoint) actual real response to the same prompt.

    Deliberately does NOT ask any model to fabricate fresh harmful compliant
    content: the "rejected" side is a genuine observed failure captured from
    a real model (nano scored 20% jailbreak-block-rate in its own red-team
    run — this reuses that exact weakness as the contrastive signal),
    not a synthetically-elicited one. Pairs are skipped whenever the weak
    model actually refused (no safety gap to correct there) or the teacher
    itself failed to refuse (would teach the wrong preference).
    """
    log = on_log or (lambda msg: None)
    domain = get_domain("safety_refusal")

    output_path = DPO_DATA_DIR / f"nano_safety_dpo_{time.strftime('%Y%m%d')}.jsonl"

    written = 0
    failed = 0
    skipped_no_gap = 0

    log(f"[dpo-safety] teacher: {teacher_model}  weak model: {weak_model}  "
        f"target: {n_examples} pairs  -> {output_path}")

    with open(output_path, "a") as out_f:
        for i in range(n_examples):
            _domain_system, prompt_text = build_prompt(domain)

            try:
                chosen = _teacher_generate(
                    prompt_text, teacher_model, "http://localhost:11434",
                    on_log=log, teacher_backend=teacher_backend,
                )
                rejected = _local_generate(prompt_text, weak_model, ollama_host)
            except Exception as e:
                failed += 1
                log(f"[dpo-safety] [{i+1}/{n_examples}] FAILED: {e}")
                continue

            if not chosen.strip() or not rejected.strip():
                failed += 1
                log(f"[dpo-safety] [{i+1}/{n_examples}] empty response, skipped")
                continue

            teacher_refused = _is_refusal(chosen)
            weak_refused = _is_refusal(rejected)

            if not teacher_refused:
                # Teacher itself complied — using this as "chosen" would
                # teach the opposite of what we want. Skip rather than risk
                # training on a bad positive example.
                failed += 1
                log(f"[dpo-safety] [{i+1}/{n_examples}] teacher did not refuse, skipped")
                continue

            if weak_refused:
                # No safety gap on this particular prompt — nothing to
                # correct here, and pairing two refusals teaches nothing.
                skipped_no_gap += 1
                log(f"[dpo-safety] [{i+1}/{n_examples}] weak model already refused, no gap, skipped")
                continue

            if chosen.strip() == rejected.strip():
                failed += 1
                log(f"[dpo-safety] [{i+1}/{n_examples}] chosen == rejected, skipped")
                continue

            record = {
                "prompt": prompt_text,
                "chosen": chosen.strip(),
                "rejected": rejected.strip(),
                "domain": domain.name,
            }
            out_f.write(json.dumps(record) + "\n")
            written += 1
            log(f"[dpo-safety] [{i+1}/{n_examples}] written (real safety gap captured)")

    result = {
        "teacher_model": teacher_model,
        "weak_model": weak_model,
        "requested": n_examples,
        "written": written,
        "failed": failed,
        "skipped_no_gap": skipped_no_gap,
        "output_file": str(output_path),
    }
    log(f"[dpo-safety] done — {written} written, {failed} failed, "
        f"{skipped_no_gap} skipped (weak model already safe on those prompts)")
    return result


def generate_probe_grounded_safety_pairs(
    teacher_model: str = "nvidia/nemotron-3-ultra-550b-a55b",
    teacher_backend: str = "auto",
    weak_model: str = "orca-nano",
    ollama_host: str = "http://localhost:11434",
    trials: int = 1,
    on_log=None,
) -> dict:
    """
    Real gap this closes: generate_safety_refusal_pairs() above trains on
    TEACHER-INVENTED synthetic adversarial prompts (seeds.py's
    safety_refusal domain generates fresh jailbreak-style questions on the
    fly) — a stylistically similar but DIFFERENT set of prompts than the
    fixed JAILBREAK_PROBES list orca/train/redteam.py actually measures
    jailbreak resistance against. The training signal and the eval target
    were never the same prompts. This function trains directly on the
    literal, exact probes being measured — closing that gap.

    trials > 1 captures the weak model's response multiple times per probe
    (matching redteam.py's own trials-averaging discipline) and only writes
    a pair if the weak model complied in EVERY trial — a probe the weak
    model sometimes refuses isn't a clean, unambiguous training signal the
    same way a probe it reliably fails on is.
    """
    log = on_log or (lambda msg: None)
    _model_slug = weak_model.replace("orca-", "").replace(":", "_")
    output_path = DPO_DATA_DIR / f"{_model_slug}_probe_grounded_safety_dpo_{time.strftime('%Y%m%d')}.jsonl"

    written = 0
    failed = 0
    skipped_no_gap = 0
    skipped_inconsistent = 0

    log(f"[dpo-probe-safety] teacher: {teacher_model}  weak model: {weak_model}  "
        f"{len(JAILBREAK_PROBES)} exact eval probes, {trials} trial(s) each -> {output_path}")

    with open(output_path, "a") as out_f:
        for i, prompt_text in enumerate(JAILBREAK_PROBES):
            try:
                chosen = _teacher_generate(
                    prompt_text, teacher_model, "http://localhost:11434",
                    on_log=log, teacher_backend=teacher_backend,
                )
                weak_responses = [_local_generate(prompt_text, weak_model, ollama_host) for _ in range(trials)]
            except Exception as e:
                failed += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] FAILED: {e}")
                continue

            if not chosen.strip() or any(not r.strip() for r in weak_responses):
                failed += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] empty response, skipped")
                continue

            teacher_refused = _is_refusal(chosen)
            if not teacher_refused:
                failed += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] teacher did not refuse, skipped")
                continue

            weak_refusals = [_is_refusal(r) for r in weak_responses]
            if all(weak_refusals):
                skipped_no_gap += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] weak model refused every trial, no gap, skipped")
                continue
            if any(weak_refusals):
                # Inconsistent across trials — same instability jailbreak
                # measurement itself showed this session (redteam block
                # rate swinging run-to-run). Not a clean signal to train on.
                skipped_inconsistent += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] inconsistent across {trials} trials, skipped")
                continue

            rejected = weak_responses[0]
            if chosen.strip() == rejected.strip():
                failed += 1
                log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] chosen == rejected, skipped")
                continue

            record = {
                "prompt": prompt_text,
                "chosen": chosen.strip(),
                "rejected": rejected.strip(),
                "domain": "safety_refusal_probe_grounded",
            }
            out_f.write(json.dumps(record) + "\n")
            written += 1
            log(f"[dpo-probe-safety] [{i+1}/{len(JAILBREAK_PROBES)}] written (real, exact-probe safety gap captured)")

    result = {
        "teacher_model": teacher_model,
        "weak_model": weak_model,
        "requested": len(JAILBREAK_PROBES),
        "written": written,
        "failed": failed,
        "skipped_no_gap": skipped_no_gap,
        "skipped_inconsistent": skipped_inconsistent,
        "output_file": str(output_path),
    }
    log(f"[dpo-probe-safety] done — {written} written, {failed} failed, "
        f"{skipped_no_gap} no-gap, {skipped_inconsistent} inconsistent")
    return result


_BIAS_MITIGATION_SYSTEM_OVERRIDE = """\
Answer the following question thoroughly and substantively, giving the same
depth, length, and quality of response you would give to any professional
regardless of the specific name, gender, or role mentioned. Do not let the
particular name or role in the question shorten your answer or push you
toward stereotyped trait language (e.g. reflexively describing one role as
"caring/supportive" and another as "confident/decisive" based on gender or
occupation stereotypes) — give a substantive, individualized response on
its own merits."""


def generate_bias_mitigation_pairs(
    redteam_report_path: Path | str,
    teacher_model: str = "nvidia/nemotron-3-ultra-550b-a55b",
    teacher_backend: str = "auto",
    weak_model: str = "orca-nano",
    ollama_host: str = "http://localhost:11434",
    on_log=None,
) -> dict:
    """
    Generates (prompt, chosen, rejected) triples FROM A REAL RED-TEAM
    REPORT's actually-flagged bias pairs — not blind coverage of every
    BIAS_PROBE_PAIRS entry. Grounds the training data in the specific
    prompts where a real, repeatable divergence was measured (see
    orca/train/redteam.py's trials-averaging — a pair should have been
    flagged at trials=3+, not a single noisy sample, before being worth a
    dedicated fix here).

    Unlike the honesty/safety pairs (one prompt, two contrasting answers to
    THAT prompt), a bias pair is fundamentally about two DIFFERENT prompts
    (e.g. "...named Michael" vs "...named Michelle") diverging from each
    other. DPO needs a single prompt per example, so this treats each side
    of a flagged pair as its own independent DPO example: chosen = the
    teacher's response when explicitly instructed to answer with consistent
    depth/quality regardless of the name/role (see
    _BIAS_MITIGATION_SYSTEM_OVERRIDE), rejected = the WEAK model's own real
    response to that same specific prompt — same self-distillation
    principle as generate_safety_refusal_pairs (real observed behavior, not
    synthetic).

    Returns a summary dict — counts, output file, failures.
    """
    log = on_log or (lambda msg: None)

    report = json.loads(Path(redteam_report_path).read_text())
    flagged_pairs = report.get("bias", {}).get("flagged_pairs", [])
    if not flagged_pairs:
        log("[dpo-bias] no flagged bias pairs in this report — nothing to generate")
        return {"requested": 0, "written": 0, "failed": 0, "output_file": None}

    # Each flagged pair contributes both of its prompts as independent jobs.
    prompts = [p for fp in flagged_pairs for p in (fp["prompt_a"], fp["prompt_b"])]

    output_path = DPO_DATA_DIR / f"nano_bias_dpo_{time.strftime('%Y%m%d')}.jsonl"
    written = 0
    failed = 0

    log(f"[dpo-bias] teacher: {teacher_model}  weak model: {weak_model}  "
        f"{len(flagged_pairs)} flagged pairs -> {len(prompts)} prompts -> {output_path}")

    with open(output_path, "a") as out_f:
        for i, prompt_text in enumerate(prompts):
            try:
                chosen = _teacher_generate(
                    _BIAS_MITIGATION_SYSTEM_OVERRIDE + "\n\nQuestion: " + prompt_text,
                    teacher_model, "http://localhost:11434",
                    on_log=log, teacher_backend=teacher_backend,
                )
                rejected = _local_generate(prompt_text, weak_model, ollama_host)
            except Exception as e:
                failed += 1
                log(f"[dpo-bias] [{i+1}/{len(prompts)}] FAILED: {e}")
                continue

            if not chosen.strip() or not rejected.strip():
                failed += 1
                log(f"[dpo-bias] [{i+1}/{len(prompts)}] empty response, skipped")
                continue
            if chosen.strip() == rejected.strip():
                failed += 1
                log(f"[dpo-bias] [{i+1}/{len(prompts)}] chosen == rejected, skipped")
                continue

            record = {
                "prompt": prompt_text,
                "chosen": chosen.strip(),
                "rejected": rejected.strip(),
                "domain": "bias_mitigation",
            }
            out_f.write(json.dumps(record) + "\n")
            written += 1
            log(f"[dpo-bias] [{i+1}/{len(prompts)}] written")

    result = {
        "teacher_model": teacher_model,
        "weak_model": weak_model,
        "requested": len(prompts),
        "written": written,
        "failed": failed,
        "output_file": str(output_path),
    }
    log(f"[dpo-bias] done — {written} written, {failed} failed")
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--n", type=int, default=100)
    parser.add_argument("--teacher", default="nvidia/nemotron-3-ultra-550b-a55b")
    parser.add_argument("--backend", default="auto", choices=["auto", "openrouter"])
    parser.add_argument("--domain", default="honesty_hedging",
                         choices=["honesty_hedging", "safety_refusal", "safety_refusal_probe_grounded", "bias_mitigation"])
    parser.add_argument("--weak-model", default="orca-nano", help="Used for --domain safety_refusal/bias_mitigation")
    parser.add_argument("--trials", type=int, default=1, help="Used for --domain safety_refusal_probe_grounded")
    parser.add_argument("--redteam-report", default=None,
                         help="Path to a redteam JSON report — required for --domain bias_mitigation")
    args = parser.parse_args()

    def log(msg):
        print(msg, flush=True)

    if args.domain == "safety_refusal_probe_grounded":
        result = generate_probe_grounded_safety_pairs(
            teacher_model=args.teacher, teacher_backend=args.backend,
            weak_model=args.weak_model, trials=args.trials, on_log=log,
        )
    elif args.domain == "safety_refusal":
        result = generate_safety_refusal_pairs(
            args.n, teacher_model=args.teacher, teacher_backend=args.backend,
            weak_model=args.weak_model, on_log=log,
        )
    elif args.domain == "bias_mitigation":
        if not args.redteam_report:
            raise SystemExit("--redteam-report is required for --domain bias_mitigation")
        result = generate_bias_mitigation_pairs(
            args.redteam_report, teacher_model=args.teacher, teacher_backend=args.backend,
            weak_model=args.weak_model, on_log=log,
        )
    else:
        result = generate_dpo_pairs(args.n, teacher_model=args.teacher, teacher_backend=args.backend, on_log=log)

    print(f"\nDPO pairs — {result['written']} written, {result['failed']} failed")
    print(f"Output: {result['output_file']}")


if __name__ == "__main__":
    main()
